name: Update contributors

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Update contributors list in README.md
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          image_size: 100
          readme_path: README.md
          use_username: true
          columns_per_row: 6
          collaborators: all
          commit_message: update contributor
          committer_username: okatu-loli
          committer_email: CN_QianShi@hotmail.com
          auto_detect_branch_protection: true
          pr_title_on_protected: docs(contributor): contributors readme action update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
